const Cog = require("@glowbot/cogs")
const cog = new Cog("./cogs")
console.log(cog)
cog.loadAll()
console.log(cog)
cog.unloadAll()
console.log(cog)
cog.loadAll()
cog.unload("1")
console.log(cog)
cog.load("1")
console.log(cog)